title: "ImX6 공식 블로그"
author: "KIM MINJU"
description: "AI 3D 굿즈 및 주얼리 제작 매거진"

# 블로그 주소 설정
url: "https://blog.imagetogoods.com"
baseurl: ""

# 테마 및 플러그인
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-remote-theme
  - jekyll-toc
  - jekyll-seo-tag

# 사이드바 메뉴 순서 설정 (이 부분이 있어야 글이 보입니다)
ordered_collections:
  - posts

# 목차 설정
toc:
  enabled: true
  h_min: 1
  h_max: 3

# 카테고리 정의 (아까 포스팅에 적은 이름들과 똑같아야 합니다)
categories: [Brand Story, 3D Goods, 14K Jewelry, Notice]

# Markdown 및 하이라이트 설정
kramdown:
  input: GFM
  syntax_highlighter: rouge
